name: kitx_shared_dart
description: A port of KitX.Shared in dart
version: 3.24.10+6829-patch-1
repository: https://github.com/Crequency/KitX-Standard/KitX.Shared.Dart/

environment:
  sdk: ^3.3.0

dependencies:
  built_collection: ^5.1.1
  built_value: ^8.8.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  # Run `dart run build_runner build` to generate `.g.dart` files.
  # You can also execute `build_runner.ps1` with pwsh to run the command.
  build_runner: ^2.4.8
  built_value_generator: ^8.8.1
