name: kitx_shared_dart
description: A port of KitX.Shared in dart
version: 1.0.0
repository: https://github.com/Crequency/KitX-Standard/KitX.Shared.Dart/

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
